import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/layout/NavigationMenu";

import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import FooterComponent from "@/components/layout/FooterComponent";

config.autoAddCss = false

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" data-theme="bumblebee">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NavigationMenu/>
        {children}
        <FooterComponent/>
        </body>
        </html>
    );
}
